#!/bin/bash
MYDIR=$(dirname `realpath $0`)

echo Cleaning up existing dotfiles...
rm -rf $HOME/.vimrc $HOME/.bashrc $HOME/.ssh/config $HOME/.vim &> /dev/null

echo Symlinking dotfiles...
ln -s "${MYDIR}/vimrc" "$HOME/.vimrc"
ln -s "${MYDIR}/bashrc" "$HOME/.bashrc"
mkdir -p "${HOME}/.ssh"
ln -s "${MYDIR}/sshconfig" "$HOME/.ssh/config"
ln -s "${MYDIR}/vim" "${HOME}/.vim"
